### ISSUE TITLE
META issue : Bugs related to bluetooth functionality merged through #2

### ISSUE THREAD

**Issue by kdexd** [hareshkh/tic-tac-toe-android-app#3]
This issue holds a broad sense of an array of bugs existing in current P2P implementation of the game.
- All the issues will be quantized and broken into little parts and a **checklist** will be maintained here.
- When the checklist is all done, this META issue will be closed. **Till then it will remain open.**
- Each time the sub-issues are closed, reference this meta issue there and close them, to keep a track.

**Comment by karandesai-96** [comment]
@hareshkh You can maintain a checklist here...

I can do that, but if you maintain it, it would be easier for you to keep a track, as you can edit your own comments.

I just opened an issue for bluetooth which qualifies as a sub issue related to this topic.

Comment this as it is : 
```
**So the checklist for issues open so far is** :

- [ ] #4 Bluetooth button does not show ON/ OFF properly.
```

**Comment by harjot-oberai** [comment]
**So the checklist for issues open so far is** :
- [x] #4 Bluetooth button does not show ON/ OFF properly.
- [x] #6 Game ending dialogue problem
- [x] #8 Bluetooth needs to be restarted to reconnect the two devices
- [x] #10 Option for rematch between same players not available
- [x] #13 Support for lower android versions needed
- [x] #16 Database support for P2P
- [x] #17 Thickness of lines
- [ ] #18 Database not working for lower API devices

**Comment by hareshkh** [comment]
#6 Fixed and #8 added to checklist

**Comment by kdexd** [comment]
@harjot-oberai you can edit your comment and put and "X" in the square brackets of list, to show up a tick mark -- it will ease things up.

**Comment by hareshkh** [comment]
@karandesai-96 I did that. Two more issues left.
